### PR TITLE
Register commands

### PR DESCRIPTION
**Pull request by AxillityDev**
*Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?*: yep

*Votre code se compile t-il en local ?*:  yep

*Avez-vous supprimez les imports inutilisés ?*: 
## Decrivez vos changements
*Clairement et avec des screenshots si nécessaires*

j'ai oublie de register la command 🤦

### CODE REVIEW

**Comment by AxillityDev** [comment]
j'ai oublie tpacommandgui.java c'est pas une commande

**Comment by AxillityDev** [comment]
@MathiasDPX c bon

**Comment by AxenoDev** [comment]
Tu n'a pas besoins de modifie le plugin.yml

**Comment by AxillityDev** [comment]
> Tu n'a pas besoins de modifie le plugin.yml

j'ai juste add une permission

**Comment by AxillityDev** [comment]
qui peut merge cela

**Comment by Margouta** [comment]
@AxillityDev je revert :
`[11:24:03 ERROR]: Error occurred while enabling AywenCraftPlugin v1.0-SNAPSHOT (Is it up to date?)
java.lang.IllegalStateException: A command with path 'tpcancel' already exists!
        at AywenCraft.jar/revxrsal.commands.core.CommandParser.putOrError(CommandParser.java:563) ~[AywenCraft.jar:?]
        at AywenCraft.jar/revxrsal.commands.core.CommandParser.lambda$parse$4(CommandParser.java:203) ~[AywenCraft.jar:?]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at AywenCraft.jar/revxrsal.commands.core.CommandParser.parse(CommandParser.java:168) ~[AywenCraft.jar:?]
        at AywenCraft.jar/revxrsal.commands.core.CommandParser.parse(CommandParser.java:121) ~[AywenCraft.jar:?]
        at AywenCraft.jar/revxrsal.commands.core.BaseCommandHandler.register(BaseCommandHandler.java:188) ~[AywenCraft.jar:?]
        at AywenCraft.jar/revxrsal.commands.bukkit.core.BukkitHandler.register(BukkitHandler.java:149) ~[AywenCraft.jar:?]
        at AywenCraft.jar/fr.communaywen.core.AywenCraftPlugin.onEnable(AywenCraftPlugin.java:176) ~[AywenCraft.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2281-7950960]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2281-7950960]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.jar:1.21-2281-7950960]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.jar:1.21-2281-7950960]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.jar:1.21-2281-7950960]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.jar:1.21-2281-7950960]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.jar:1.21-2281-7950960]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.jar:1.21-2281-7950960]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2281-7950960]`

**Pull request merged**
